# ===============================
# SERVER
# ===============================

# ===============================
# DATABASE CONFIGURATION
# ===============================
#spring.datasource.url=
#
#spring.datasource.username=ritika
#spring.datasource.password=Ritika@123
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## ===============================
## JPA
## ===============================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## ===============================
## CONNECTION POOL
## ===============================
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.connection-timeout=30000




# =================================================================
# Database Connection Settings (Supabase)
# =================================================================
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/codecluster?sslmode=require

spring.datasource.username=ritika.yzbpgxbhctavmuojaxyf
spring.datasource.password=Ritika@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# =========================
# JWT Configuration
# =========================

jwt.secret=ReplaceThisWithYourVeryLongSecretKeyThatIsAtLeast32CharactersLong123456

jwt.access-token-expiration=900000

jwt.refresh-token-expiration=604800000

